route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: receiver@gmail.com
    from: sender@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "sender@gmail.com"
    auth_identity: "sender@gmail.com"
    auth_password: "**********************"
